### ISSUE TITLE
Развернуть среду разработки windowbuilder

### ISSUE THREAD

**Issue by nmivan** [oknosoft/windowbuilder-planning#3]
По дороге встретилась неприятность - запросы к CouchDB стали падать по таймауту (10000), не читались цены и характеристики (запрос http://localhost:5984/wb_21_doc/_design/doc/_view/nom_characteristics?include_docs=true&limit=1000&startkey=%22cat.characteristics%7C%22&endkey=%22cat.characteristics%7C%EF%BF%B0%22)

Оказалось, дело в параметре CouchDB reduce_limit. Если он стоит в true, и запрос тяжелый, то CouchDB возвращает ошибку reduce_overflow_error, и загрузка wb останавливается (зависает).

Вероятно, надо в таком случае лимит уменьшать, или таймаут увеличивать и повторять запрос. Пока просто поставил reduce_limit = true.

**Comment by unpete** [comment]
Тяжесть запроса здесь ни при чем - просто по времени совпало, а
reduce_limit, наверное, должен быть false, чтобы не ограничивать размер
возвращаемого редюсом значения.
